#! /bin/bash

set -e

clang_format="${CLANG_FORMAT_VERSION:-clang-format-13}"
origin="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
root="${origin}/.."
find "${root}" -type f \
    -regex '^.*\.cpp$' \
    -o -regex '^.*\.hpp$' \
    -o -regex '^.*\.h$' \
    -o -regex '^.*\.c$' \
    | parallel "${clang_format}" --dry-run -Werror
