// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MATSimInterface.proto

#ifndef PROTOBUF_MATSimInterface_2eproto__INCLUDED
#define PROTOBUF_MATSimInterface_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MATSimInterface_2eproto();
void protobuf_AssignDesc_MATSimInterface_2eproto();
void protobuf_ShutdownFile_MATSimInterface_2eproto();

class MATSim2ExternPutAgent;
class MATSim2ExternPutAgent_Agent;
class MATSim2ExternHasSpace;
class MATSim2ExternHasSpaceConfirmed;
class MATSim2ExternPutAgentConfirmed;
class Extern2MATSim;
class Extern2MATSim_Agent;
class Extern2MATSimConfirmed;
class ExternSimStepFinished;
class ExternSimStepFinishedReceived;
class ExternDoSimStep;
class ExternDoSimStepReceived;
class ExternalConnect;
class ExternalConnectConfirmed;
class ExternOnPrepareSim;
class ExternOnPrepareSimConfirmed;
class ExternAfterSim;
class ExternAfterSimConfirmed;
class AgentsStuck;
class AgentsStuckConfirmed;

// ===================================================================

class MATSim2ExternPutAgent_Agent : public ::google::protobuf::Message {
 public:
  MATSim2ExternPutAgent_Agent();
  virtual ~MATSim2ExternPutAgent_Agent();

  MATSim2ExternPutAgent_Agent(const MATSim2ExternPutAgent_Agent& from);

  inline MATSim2ExternPutAgent_Agent& operator=(const MATSim2ExternPutAgent_Agent& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MATSim2ExternPutAgent_Agent& default_instance();

  void Swap(MATSim2ExternPutAgent_Agent* other);

  // implements Message ----------------------------------------------

  MATSim2ExternPutAgent_Agent* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MATSim2ExternPutAgent_Agent& from);
  void MergeFrom(const MATSim2ExternPutAgent_Agent& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline const ::std::string& id() const;
  inline void set_id(const ::std::string& value);
  inline void set_id(const char* value);
  inline void set_id(const char* value, size_t size);
  inline ::std::string* mutable_id();
  inline ::std::string* release_id();
  inline void set_allocated_id(::std::string* id);

  // required string enterNode = 2;
  inline bool has_enternode() const;
  inline void clear_enternode();
  static const int kEnterNodeFieldNumber = 2;
  inline const ::std::string& enternode() const;
  inline void set_enternode(const ::std::string& value);
  inline void set_enternode(const char* value);
  inline void set_enternode(const char* value, size_t size);
  inline ::std::string* mutable_enternode();
  inline ::std::string* release_enternode();
  inline void set_allocated_enternode(::std::string* enternode);

  // repeated string nodes = 3;
  inline int nodes_size() const;
  inline void clear_nodes();
  static const int kNodesFieldNumber = 3;
  inline const ::std::string& nodes(int index) const;
  inline ::std::string* mutable_nodes(int index);
  inline void set_nodes(int index, const ::std::string& value);
  inline void set_nodes(int index, const char* value);
  inline void set_nodes(int index, const char* value, size_t size);
  inline ::std::string* add_nodes();
  inline void add_nodes(const ::std::string& value);
  inline void add_nodes(const char* value);
  inline void add_nodes(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& nodes() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_nodes();

  // @@protoc_insertion_point(class_scope:MATSim2ExternPutAgent.Agent)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_enternode();
  inline void clear_has_enternode();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* id_;
  ::std::string* enternode_;
  ::google::protobuf::RepeatedPtrField< ::std::string> nodes_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_MATSimInterface_2eproto();
  friend void protobuf_AssignDesc_MATSimInterface_2eproto();
  friend void protobuf_ShutdownFile_MATSimInterface_2eproto();

  void InitAsDefaultInstance();
  static MATSim2ExternPutAgent_Agent* default_instance_;
};
// -------------------------------------------------------------------

class MATSim2ExternPutAgent : public ::google::protobuf::Message {
 public:
  MATSim2ExternPutAgent();
  virtual ~MATSim2ExternPutAgent();

  MATSim2ExternPutAgent(const MATSim2ExternPutAgent& from);

  inline MATSim2ExternPutAgent& operator=(const MATSim2ExternPutAgent& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MATSim2ExternPutAgent& default_instance();

  void Swap(MATSim2ExternPutAgent* other);

  // implements Message ----------------------------------------------

  MATSim2ExternPutAgent* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MATSim2ExternPutAgent& from);
  void MergeFrom(const MATSim2ExternPutAgent& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef MATSim2ExternPutAgent_Agent Agent;

  // accessors -------------------------------------------------------

  // required .MATSim2ExternPutAgent.Agent agent = 1;
  inline bool has_agent() const;
  inline void clear_agent();
  static const int kAgentFieldNumber = 1;
  inline const ::MATSim2ExternPutAgent_Agent& agent() const;
  inline ::MATSim2ExternPutAgent_Agent* mutable_agent();
  inline ::MATSim2ExternPutAgent_Agent* release_agent();
  inline void set_allocated_agent(::MATSim2ExternPutAgent_Agent* agent);

  // @@protoc_insertion_point(class_scope:MATSim2ExternPutAgent)
 private:
  inline void set_has_agent();
  inline void clear_has_agent();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::MATSim2ExternPutAgent_Agent* agent_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_MATSimInterface_2eproto();
  friend void protobuf_AssignDesc_MATSimInterface_2eproto();
  friend void protobuf_ShutdownFile_MATSimInterface_2eproto();

  void InitAsDefaultInstance();
  static MATSim2ExternPutAgent* default_instance_;
};
// -------------------------------------------------------------------

class MATSim2ExternHasSpace : public ::google::protobuf::Message {
 public:
  MATSim2ExternHasSpace();
  virtual ~MATSim2ExternHasSpace();

  MATSim2ExternHasSpace(const MATSim2ExternHasSpace& from);

  inline MATSim2ExternHasSpace& operator=(const MATSim2ExternHasSpace& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MATSim2ExternHasSpace& default_instance();

  void Swap(MATSim2ExternHasSpace* other);

  // implements Message ----------------------------------------------

  MATSim2ExternHasSpace* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MATSim2ExternHasSpace& from);
  void MergeFrom(const MATSim2ExternHasSpace& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string nodeId = 1;
  inline bool has_nodeid() const;
  inline void clear_nodeid();
  static const int kNodeIdFieldNumber = 1;
  inline const ::std::string& nodeid() const;
  inline void set_nodeid(const ::std::string& value);
  inline void set_nodeid(const char* value);
  inline void set_nodeid(const char* value, size_t size);
  inline ::std::string* mutable_nodeid();
  inline ::std::string* release_nodeid();
  inline void set_allocated_nodeid(::std::string* nodeid);

  // @@protoc_insertion_point(class_scope:MATSim2ExternHasSpace)
 private:
  inline void set_has_nodeid();
  inline void clear_has_nodeid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* nodeid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_MATSimInterface_2eproto();
  friend void protobuf_AssignDesc_MATSimInterface_2eproto();
  friend void protobuf_ShutdownFile_MATSimInterface_2eproto();

  void InitAsDefaultInstance();
  static MATSim2ExternHasSpace* default_instance_;
};
// -------------------------------------------------------------------

class MATSim2ExternHasSpaceConfirmed : public ::google::protobuf::Message {
 public:
  MATSim2ExternHasSpaceConfirmed();
  virtual ~MATSim2ExternHasSpaceConfirmed();

  MATSim2ExternHasSpaceConfirmed(const MATSim2ExternHasSpaceConfirmed& from);

  inline MATSim2ExternHasSpaceConfirmed& operator=(const MATSim2ExternHasSpaceConfirmed& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MATSim2ExternHasSpaceConfirmed& default_instance();

  void Swap(MATSim2ExternHasSpaceConfirmed* other);

  // implements Message ----------------------------------------------

  MATSim2ExternHasSpaceConfirmed* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MATSim2ExternHasSpaceConfirmed& from);
  void MergeFrom(const MATSim2ExternHasSpaceConfirmed& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bool hasSpace = 1;
  inline bool has_hasspace() const;
  inline void clear_hasspace();
  static const int kHasSpaceFieldNumber = 1;
  inline bool hasspace() const;
  inline void set_hasspace(bool value);

  // @@protoc_insertion_point(class_scope:MATSim2ExternHasSpaceConfirmed)
 private:
  inline void set_has_hasspace();
  inline void clear_has_hasspace();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  bool hasspace_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_MATSimInterface_2eproto();
  friend void protobuf_AssignDesc_MATSimInterface_2eproto();
  friend void protobuf_ShutdownFile_MATSimInterface_2eproto();

  void InitAsDefaultInstance();
  static MATSim2ExternHasSpaceConfirmed* default_instance_;
};
// -------------------------------------------------------------------

class MATSim2ExternPutAgentConfirmed : public ::google::protobuf::Message {
 public:
  MATSim2ExternPutAgentConfirmed();
  virtual ~MATSim2ExternPutAgentConfirmed();

  MATSim2ExternPutAgentConfirmed(const MATSim2ExternPutAgentConfirmed& from);

  inline MATSim2ExternPutAgentConfirmed& operator=(const MATSim2ExternPutAgentConfirmed& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MATSim2ExternPutAgentConfirmed& default_instance();

  void Swap(MATSim2ExternPutAgentConfirmed* other);

  // implements Message ----------------------------------------------

  MATSim2ExternPutAgentConfirmed* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MATSim2ExternPutAgentConfirmed& from);
  void MergeFrom(const MATSim2ExternPutAgentConfirmed& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:MATSim2ExternPutAgentConfirmed)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_MATSimInterface_2eproto();
  friend void protobuf_AssignDesc_MATSimInterface_2eproto();
  friend void protobuf_ShutdownFile_MATSimInterface_2eproto();

  void InitAsDefaultInstance();
  static MATSim2ExternPutAgentConfirmed* default_instance_;
};
// -------------------------------------------------------------------

class Extern2MATSim_Agent : public ::google::protobuf::Message {
 public:
  Extern2MATSim_Agent();
  virtual ~Extern2MATSim_Agent();

  Extern2MATSim_Agent(const Extern2MATSim_Agent& from);

  inline Extern2MATSim_Agent& operator=(const Extern2MATSim_Agent& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Extern2MATSim_Agent& default_instance();

  void Swap(Extern2MATSim_Agent* other);

  // implements Message ----------------------------------------------

  Extern2MATSim_Agent* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Extern2MATSim_Agent& from);
  void MergeFrom(const Extern2MATSim_Agent& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline const ::std::string& id() const;
  inline void set_id(const ::std::string& value);
  inline void set_id(const char* value);
  inline void set_id(const char* value, size_t size);
  inline ::std::string* mutable_id();
  inline ::std::string* release_id();
  inline void set_allocated_id(::std::string* id);

  // required string leaveNode = 2;
  inline bool has_leavenode() const;
  inline void clear_leavenode();
  static const int kLeaveNodeFieldNumber = 2;
  inline const ::std::string& leavenode() const;
  inline void set_leavenode(const ::std::string& value);
  inline void set_leavenode(const char* value);
  inline void set_leavenode(const char* value, size_t size);
  inline ::std::string* mutable_leavenode();
  inline ::std::string* release_leavenode();
  inline void set_allocated_leavenode(::std::string* leavenode);

  // @@protoc_insertion_point(class_scope:Extern2MATSim.Agent)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_leavenode();
  inline void clear_has_leavenode();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* id_;
  ::std::string* leavenode_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_MATSimInterface_2eproto();
  friend void protobuf_AssignDesc_MATSimInterface_2eproto();
  friend void protobuf_ShutdownFile_MATSimInterface_2eproto();

  void InitAsDefaultInstance();
  static Extern2MATSim_Agent* default_instance_;
};
// -------------------------------------------------------------------

class Extern2MATSim : public ::google::protobuf::Message {
 public:
  Extern2MATSim();
  virtual ~Extern2MATSim();

  Extern2MATSim(const Extern2MATSim& from);

  inline Extern2MATSim& operator=(const Extern2MATSim& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Extern2MATSim& default_instance();

  void Swap(Extern2MATSim* other);

  // implements Message ----------------------------------------------

  Extern2MATSim* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Extern2MATSim& from);
  void MergeFrom(const Extern2MATSim& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Extern2MATSim_Agent Agent;

  // accessors -------------------------------------------------------

  // required .Extern2MATSim.Agent agent = 15;
  inline bool has_agent() const;
  inline void clear_agent();
  static const int kAgentFieldNumber = 15;
  inline const ::Extern2MATSim_Agent& agent() const;
  inline ::Extern2MATSim_Agent* mutable_agent();
  inline ::Extern2MATSim_Agent* release_agent();
  inline void set_allocated_agent(::Extern2MATSim_Agent* agent);

  // @@protoc_insertion_point(class_scope:Extern2MATSim)
 private:
  inline void set_has_agent();
  inline void clear_has_agent();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::Extern2MATSim_Agent* agent_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_MATSimInterface_2eproto();
  friend void protobuf_AssignDesc_MATSimInterface_2eproto();
  friend void protobuf_ShutdownFile_MATSimInterface_2eproto();

  void InitAsDefaultInstance();
  static Extern2MATSim* default_instance_;
};
// -------------------------------------------------------------------

class Extern2MATSimConfirmed : public ::google::protobuf::Message {
 public:
  Extern2MATSimConfirmed();
  virtual ~Extern2MATSimConfirmed();

  Extern2MATSimConfirmed(const Extern2MATSimConfirmed& from);

  inline Extern2MATSimConfirmed& operator=(const Extern2MATSimConfirmed& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Extern2MATSimConfirmed& default_instance();

  void Swap(Extern2MATSimConfirmed* other);

  // implements Message ----------------------------------------------

  Extern2MATSimConfirmed* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Extern2MATSimConfirmed& from);
  void MergeFrom(const Extern2MATSimConfirmed& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bool accepted = 1;
  inline bool has_accepted() const;
  inline void clear_accepted();
  static const int kAcceptedFieldNumber = 1;
  inline bool accepted() const;
  inline void set_accepted(bool value);

  // @@protoc_insertion_point(class_scope:Extern2MATSimConfirmed)
 private:
  inline void set_has_accepted();
  inline void clear_has_accepted();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  bool accepted_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_MATSimInterface_2eproto();
  friend void protobuf_AssignDesc_MATSimInterface_2eproto();
  friend void protobuf_ShutdownFile_MATSimInterface_2eproto();

  void InitAsDefaultInstance();
  static Extern2MATSimConfirmed* default_instance_;
};
// -------------------------------------------------------------------

class ExternSimStepFinished : public ::google::protobuf::Message {
 public:
  ExternSimStepFinished();
  virtual ~ExternSimStepFinished();

  ExternSimStepFinished(const ExternSimStepFinished& from);

  inline ExternSimStepFinished& operator=(const ExternSimStepFinished& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ExternSimStepFinished& default_instance();

  void Swap(ExternSimStepFinished* other);

  // implements Message ----------------------------------------------

  ExternSimStepFinished* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ExternSimStepFinished& from);
  void MergeFrom(const ExternSimStepFinished& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double time = 1;
  inline bool has_time() const;
  inline void clear_time();
  static const int kTimeFieldNumber = 1;
  inline double time() const;
  inline void set_time(double value);

  // @@protoc_insertion_point(class_scope:ExternSimStepFinished)
 private:
  inline void set_has_time();
  inline void clear_has_time();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  double time_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_MATSimInterface_2eproto();
  friend void protobuf_AssignDesc_MATSimInterface_2eproto();
  friend void protobuf_ShutdownFile_MATSimInterface_2eproto();

  void InitAsDefaultInstance();
  static ExternSimStepFinished* default_instance_;
};
// -------------------------------------------------------------------

class ExternSimStepFinishedReceived : public ::google::protobuf::Message {
 public:
  ExternSimStepFinishedReceived();
  virtual ~ExternSimStepFinishedReceived();

  ExternSimStepFinishedReceived(const ExternSimStepFinishedReceived& from);

  inline ExternSimStepFinishedReceived& operator=(const ExternSimStepFinishedReceived& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ExternSimStepFinishedReceived& default_instance();

  void Swap(ExternSimStepFinishedReceived* other);

  // implements Message ----------------------------------------------

  ExternSimStepFinishedReceived* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ExternSimStepFinishedReceived& from);
  void MergeFrom(const ExternSimStepFinishedReceived& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:ExternSimStepFinishedReceived)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_MATSimInterface_2eproto();
  friend void protobuf_AssignDesc_MATSimInterface_2eproto();
  friend void protobuf_ShutdownFile_MATSimInterface_2eproto();

  void InitAsDefaultInstance();
  static ExternSimStepFinishedReceived* default_instance_;
};
// -------------------------------------------------------------------

class ExternDoSimStep : public ::google::protobuf::Message {
 public:
  ExternDoSimStep();
  virtual ~ExternDoSimStep();

  ExternDoSimStep(const ExternDoSimStep& from);

  inline ExternDoSimStep& operator=(const ExternDoSimStep& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ExternDoSimStep& default_instance();

  void Swap(ExternDoSimStep* other);

  // implements Message ----------------------------------------------

  ExternDoSimStep* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ExternDoSimStep& from);
  void MergeFrom(const ExternDoSimStep& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double fromTime = 1;
  inline bool has_fromtime() const;
  inline void clear_fromtime();
  static const int kFromTimeFieldNumber = 1;
  inline double fromtime() const;
  inline void set_fromtime(double value);

  // required double toTime = 2;
  inline bool has_totime() const;
  inline void clear_totime();
  static const int kToTimeFieldNumber = 2;
  inline double totime() const;
  inline void set_totime(double value);

  // @@protoc_insertion_point(class_scope:ExternDoSimStep)
 private:
  inline void set_has_fromtime();
  inline void clear_has_fromtime();
  inline void set_has_totime();
  inline void clear_has_totime();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  double fromtime_;
  double totime_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_MATSimInterface_2eproto();
  friend void protobuf_AssignDesc_MATSimInterface_2eproto();
  friend void protobuf_ShutdownFile_MATSimInterface_2eproto();

  void InitAsDefaultInstance();
  static ExternDoSimStep* default_instance_;
};
// -------------------------------------------------------------------

class ExternDoSimStepReceived : public ::google::protobuf::Message {
 public:
  ExternDoSimStepReceived();
  virtual ~ExternDoSimStepReceived();

  ExternDoSimStepReceived(const ExternDoSimStepReceived& from);

  inline ExternDoSimStepReceived& operator=(const ExternDoSimStepReceived& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ExternDoSimStepReceived& default_instance();

  void Swap(ExternDoSimStepReceived* other);

  // implements Message ----------------------------------------------

  ExternDoSimStepReceived* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ExternDoSimStepReceived& from);
  void MergeFrom(const ExternDoSimStepReceived& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:ExternDoSimStepReceived)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_MATSimInterface_2eproto();
  friend void protobuf_AssignDesc_MATSimInterface_2eproto();
  friend void protobuf_ShutdownFile_MATSimInterface_2eproto();

  void InitAsDefaultInstance();
  static ExternDoSimStepReceived* default_instance_;
};
// -------------------------------------------------------------------

class ExternalConnect : public ::google::protobuf::Message {
 public:
  ExternalConnect();
  virtual ~ExternalConnect();

  ExternalConnect(const ExternalConnect& from);

  inline ExternalConnect& operator=(const ExternalConnect& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ExternalConnect& default_instance();

  void Swap(ExternalConnect* other);

  // implements Message ----------------------------------------------

  ExternalConnect* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ExternalConnect& from);
  void MergeFrom(const ExternalConnect& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:ExternalConnect)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_MATSimInterface_2eproto();
  friend void protobuf_AssignDesc_MATSimInterface_2eproto();
  friend void protobuf_ShutdownFile_MATSimInterface_2eproto();

  void InitAsDefaultInstance();
  static ExternalConnect* default_instance_;
};
// -------------------------------------------------------------------

class ExternalConnectConfirmed : public ::google::protobuf::Message {
 public:
  ExternalConnectConfirmed();
  virtual ~ExternalConnectConfirmed();

  ExternalConnectConfirmed(const ExternalConnectConfirmed& from);

  inline ExternalConnectConfirmed& operator=(const ExternalConnectConfirmed& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ExternalConnectConfirmed& default_instance();

  void Swap(ExternalConnectConfirmed* other);

  // implements Message ----------------------------------------------

  ExternalConnectConfirmed* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ExternalConnectConfirmed& from);
  void MergeFrom(const ExternalConnectConfirmed& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:ExternalConnectConfirmed)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_MATSimInterface_2eproto();
  friend void protobuf_AssignDesc_MATSimInterface_2eproto();
  friend void protobuf_ShutdownFile_MATSimInterface_2eproto();

  void InitAsDefaultInstance();
  static ExternalConnectConfirmed* default_instance_;
};
// -------------------------------------------------------------------

class ExternOnPrepareSim : public ::google::protobuf::Message {
 public:
  ExternOnPrepareSim();
  virtual ~ExternOnPrepareSim();

  ExternOnPrepareSim(const ExternOnPrepareSim& from);

  inline ExternOnPrepareSim& operator=(const ExternOnPrepareSim& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ExternOnPrepareSim& default_instance();

  void Swap(ExternOnPrepareSim* other);

  // implements Message ----------------------------------------------

  ExternOnPrepareSim* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ExternOnPrepareSim& from);
  void MergeFrom(const ExternOnPrepareSim& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:ExternOnPrepareSim)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_MATSimInterface_2eproto();
  friend void protobuf_AssignDesc_MATSimInterface_2eproto();
  friend void protobuf_ShutdownFile_MATSimInterface_2eproto();

  void InitAsDefaultInstance();
  static ExternOnPrepareSim* default_instance_;
};
// -------------------------------------------------------------------

class ExternOnPrepareSimConfirmed : public ::google::protobuf::Message {
 public:
  ExternOnPrepareSimConfirmed();
  virtual ~ExternOnPrepareSimConfirmed();

  ExternOnPrepareSimConfirmed(const ExternOnPrepareSimConfirmed& from);

  inline ExternOnPrepareSimConfirmed& operator=(const ExternOnPrepareSimConfirmed& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ExternOnPrepareSimConfirmed& default_instance();

  void Swap(ExternOnPrepareSimConfirmed* other);

  // implements Message ----------------------------------------------

  ExternOnPrepareSimConfirmed* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ExternOnPrepareSimConfirmed& from);
  void MergeFrom(const ExternOnPrepareSimConfirmed& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:ExternOnPrepareSimConfirmed)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_MATSimInterface_2eproto();
  friend void protobuf_AssignDesc_MATSimInterface_2eproto();
  friend void protobuf_ShutdownFile_MATSimInterface_2eproto();

  void InitAsDefaultInstance();
  static ExternOnPrepareSimConfirmed* default_instance_;
};
// -------------------------------------------------------------------

class ExternAfterSim : public ::google::protobuf::Message {
 public:
  ExternAfterSim();
  virtual ~ExternAfterSim();

  ExternAfterSim(const ExternAfterSim& from);

  inline ExternAfterSim& operator=(const ExternAfterSim& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ExternAfterSim& default_instance();

  void Swap(ExternAfterSim* other);

  // implements Message ----------------------------------------------

  ExternAfterSim* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ExternAfterSim& from);
  void MergeFrom(const ExternAfterSim& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:ExternAfterSim)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_MATSimInterface_2eproto();
  friend void protobuf_AssignDesc_MATSimInterface_2eproto();
  friend void protobuf_ShutdownFile_MATSimInterface_2eproto();

  void InitAsDefaultInstance();
  static ExternAfterSim* default_instance_;
};
// -------------------------------------------------------------------

class ExternAfterSimConfirmed : public ::google::protobuf::Message {
 public:
  ExternAfterSimConfirmed();
  virtual ~ExternAfterSimConfirmed();

  ExternAfterSimConfirmed(const ExternAfterSimConfirmed& from);

  inline ExternAfterSimConfirmed& operator=(const ExternAfterSimConfirmed& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ExternAfterSimConfirmed& default_instance();

  void Swap(ExternAfterSimConfirmed* other);

  // implements Message ----------------------------------------------

  ExternAfterSimConfirmed* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ExternAfterSimConfirmed& from);
  void MergeFrom(const ExternAfterSimConfirmed& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:ExternAfterSimConfirmed)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_MATSimInterface_2eproto();
  friend void protobuf_AssignDesc_MATSimInterface_2eproto();
  friend void protobuf_ShutdownFile_MATSimInterface_2eproto();

  void InitAsDefaultInstance();
  static ExternAfterSimConfirmed* default_instance_;
};
// -------------------------------------------------------------------

class AgentsStuck : public ::google::protobuf::Message {
 public:
  AgentsStuck();
  virtual ~AgentsStuck();

  AgentsStuck(const AgentsStuck& from);

  inline AgentsStuck& operator=(const AgentsStuck& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AgentsStuck& default_instance();

  void Swap(AgentsStuck* other);

  // implements Message ----------------------------------------------

  AgentsStuck* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AgentsStuck& from);
  void MergeFrom(const AgentsStuck& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string agentId = 1;
  inline int agentid_size() const;
  inline void clear_agentid();
  static const int kAgentIdFieldNumber = 1;
  inline const ::std::string& agentid(int index) const;
  inline ::std::string* mutable_agentid(int index);
  inline void set_agentid(int index, const ::std::string& value);
  inline void set_agentid(int index, const char* value);
  inline void set_agentid(int index, const char* value, size_t size);
  inline ::std::string* add_agentid();
  inline void add_agentid(const ::std::string& value);
  inline void add_agentid(const char* value);
  inline void add_agentid(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& agentid() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_agentid();

  // @@protoc_insertion_point(class_scope:AgentsStuck)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::std::string> agentid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_MATSimInterface_2eproto();
  friend void protobuf_AssignDesc_MATSimInterface_2eproto();
  friend void protobuf_ShutdownFile_MATSimInterface_2eproto();

  void InitAsDefaultInstance();
  static AgentsStuck* default_instance_;
};
// -------------------------------------------------------------------

class AgentsStuckConfirmed : public ::google::protobuf::Message {
 public:
  AgentsStuckConfirmed();
  virtual ~AgentsStuckConfirmed();

  AgentsStuckConfirmed(const AgentsStuckConfirmed& from);

  inline AgentsStuckConfirmed& operator=(const AgentsStuckConfirmed& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AgentsStuckConfirmed& default_instance();

  void Swap(AgentsStuckConfirmed* other);

  // implements Message ----------------------------------------------

  AgentsStuckConfirmed* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AgentsStuckConfirmed& from);
  void MergeFrom(const AgentsStuckConfirmed& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:AgentsStuckConfirmed)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_MATSimInterface_2eproto();
  friend void protobuf_AssignDesc_MATSimInterface_2eproto();
  friend void protobuf_ShutdownFile_MATSimInterface_2eproto();

  void InitAsDefaultInstance();
  static AgentsStuckConfirmed* default_instance_;
};
// ===================================================================


// ===================================================================

// MATSim2ExternPutAgent_Agent

// required string id = 1;
inline bool MATSim2ExternPutAgent_Agent::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MATSim2ExternPutAgent_Agent::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MATSim2ExternPutAgent_Agent::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MATSim2ExternPutAgent_Agent::clear_id() {
  if (id_ != &::google::protobuf::internal::kEmptyString) {
    id_->clear();
  }
  clear_has_id();
}
inline const ::std::string& MATSim2ExternPutAgent_Agent::id() const {
  return *id_;
}
inline void MATSim2ExternPutAgent_Agent::set_id(const ::std::string& value) {
  set_has_id();
  if (id_ == &::google::protobuf::internal::kEmptyString) {
    id_ = new ::std::string;
  }
  id_->assign(value);
}
inline void MATSim2ExternPutAgent_Agent::set_id(const char* value) {
  set_has_id();
  if (id_ == &::google::protobuf::internal::kEmptyString) {
    id_ = new ::std::string;
  }
  id_->assign(value);
}
inline void MATSim2ExternPutAgent_Agent::set_id(const char* value, size_t size) {
  set_has_id();
  if (id_ == &::google::protobuf::internal::kEmptyString) {
    id_ = new ::std::string;
  }
  id_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MATSim2ExternPutAgent_Agent::mutable_id() {
  set_has_id();
  if (id_ == &::google::protobuf::internal::kEmptyString) {
    id_ = new ::std::string;
  }
  return id_;
}
inline ::std::string* MATSim2ExternPutAgent_Agent::release_id() {
  clear_has_id();
  if (id_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = id_;
    id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void MATSim2ExternPutAgent_Agent::set_allocated_id(::std::string* id) {
  if (id_ != &::google::protobuf::internal::kEmptyString) {
    delete id_;
  }
  if (id) {
    set_has_id();
    id_ = id;
  } else {
    clear_has_id();
    id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string enterNode = 2;
inline bool MATSim2ExternPutAgent_Agent::has_enternode() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MATSim2ExternPutAgent_Agent::set_has_enternode() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MATSim2ExternPutAgent_Agent::clear_has_enternode() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MATSim2ExternPutAgent_Agent::clear_enternode() {
  if (enternode_ != &::google::protobuf::internal::kEmptyString) {
    enternode_->clear();
  }
  clear_has_enternode();
}
inline const ::std::string& MATSim2ExternPutAgent_Agent::enternode() const {
  return *enternode_;
}
inline void MATSim2ExternPutAgent_Agent::set_enternode(const ::std::string& value) {
  set_has_enternode();
  if (enternode_ == &::google::protobuf::internal::kEmptyString) {
    enternode_ = new ::std::string;
  }
  enternode_->assign(value);
}
inline void MATSim2ExternPutAgent_Agent::set_enternode(const char* value) {
  set_has_enternode();
  if (enternode_ == &::google::protobuf::internal::kEmptyString) {
    enternode_ = new ::std::string;
  }
  enternode_->assign(value);
}
inline void MATSim2ExternPutAgent_Agent::set_enternode(const char* value, size_t size) {
  set_has_enternode();
  if (enternode_ == &::google::protobuf::internal::kEmptyString) {
    enternode_ = new ::std::string;
  }
  enternode_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MATSim2ExternPutAgent_Agent::mutable_enternode() {
  set_has_enternode();
  if (enternode_ == &::google::protobuf::internal::kEmptyString) {
    enternode_ = new ::std::string;
  }
  return enternode_;
}
inline ::std::string* MATSim2ExternPutAgent_Agent::release_enternode() {
  clear_has_enternode();
  if (enternode_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = enternode_;
    enternode_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void MATSim2ExternPutAgent_Agent::set_allocated_enternode(::std::string* enternode) {
  if (enternode_ != &::google::protobuf::internal::kEmptyString) {
    delete enternode_;
  }
  if (enternode) {
    set_has_enternode();
    enternode_ = enternode;
  } else {
    clear_has_enternode();
    enternode_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// repeated string nodes = 3;
inline int MATSim2ExternPutAgent_Agent::nodes_size() const {
  return nodes_.size();
}
inline void MATSim2ExternPutAgent_Agent::clear_nodes() {
  nodes_.Clear();
}
inline const ::std::string& MATSim2ExternPutAgent_Agent::nodes(int index) const {
  return nodes_.Get(index);
}
inline ::std::string* MATSim2ExternPutAgent_Agent::mutable_nodes(int index) {
  return nodes_.Mutable(index);
}
inline void MATSim2ExternPutAgent_Agent::set_nodes(int index, const ::std::string& value) {
  nodes_.Mutable(index)->assign(value);
}
inline void MATSim2ExternPutAgent_Agent::set_nodes(int index, const char* value) {
  nodes_.Mutable(index)->assign(value);
}
inline void MATSim2ExternPutAgent_Agent::set_nodes(int index, const char* value, size_t size) {
  nodes_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MATSim2ExternPutAgent_Agent::add_nodes() {
  return nodes_.Add();
}
inline void MATSim2ExternPutAgent_Agent::add_nodes(const ::std::string& value) {
  nodes_.Add()->assign(value);
}
inline void MATSim2ExternPutAgent_Agent::add_nodes(const char* value) {
  nodes_.Add()->assign(value);
}
inline void MATSim2ExternPutAgent_Agent::add_nodes(const char* value, size_t size) {
  nodes_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
MATSim2ExternPutAgent_Agent::nodes() const {
  return nodes_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
MATSim2ExternPutAgent_Agent::mutable_nodes() {
  return &nodes_;
}

// -------------------------------------------------------------------

// MATSim2ExternPutAgent

// required .MATSim2ExternPutAgent.Agent agent = 1;
inline bool MATSim2ExternPutAgent::has_agent() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MATSim2ExternPutAgent::set_has_agent() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MATSim2ExternPutAgent::clear_has_agent() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MATSim2ExternPutAgent::clear_agent() {
  if (agent_ != NULL) agent_->::MATSim2ExternPutAgent_Agent::Clear();
  clear_has_agent();
}
inline const ::MATSim2ExternPutAgent_Agent& MATSim2ExternPutAgent::agent() const {
  return agent_ != NULL ? *agent_ : *default_instance_->agent_;
}
inline ::MATSim2ExternPutAgent_Agent* MATSim2ExternPutAgent::mutable_agent() {
  set_has_agent();
  if (agent_ == NULL) agent_ = new ::MATSim2ExternPutAgent_Agent;
  return agent_;
}
inline ::MATSim2ExternPutAgent_Agent* MATSim2ExternPutAgent::release_agent() {
  clear_has_agent();
  ::MATSim2ExternPutAgent_Agent* temp = agent_;
  agent_ = NULL;
  return temp;
}
inline void MATSim2ExternPutAgent::set_allocated_agent(::MATSim2ExternPutAgent_Agent* agent) {
  delete agent_;
  agent_ = agent;
  if (agent) {
    set_has_agent();
  } else {
    clear_has_agent();
  }
}

// -------------------------------------------------------------------

// MATSim2ExternHasSpace

// required string nodeId = 1;
inline bool MATSim2ExternHasSpace::has_nodeid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MATSim2ExternHasSpace::set_has_nodeid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MATSim2ExternHasSpace::clear_has_nodeid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MATSim2ExternHasSpace::clear_nodeid() {
  if (nodeid_ != &::google::protobuf::internal::kEmptyString) {
    nodeid_->clear();
  }
  clear_has_nodeid();
}
inline const ::std::string& MATSim2ExternHasSpace::nodeid() const {
  return *nodeid_;
}
inline void MATSim2ExternHasSpace::set_nodeid(const ::std::string& value) {
  set_has_nodeid();
  if (nodeid_ == &::google::protobuf::internal::kEmptyString) {
    nodeid_ = new ::std::string;
  }
  nodeid_->assign(value);
}
inline void MATSim2ExternHasSpace::set_nodeid(const char* value) {
  set_has_nodeid();
  if (nodeid_ == &::google::protobuf::internal::kEmptyString) {
    nodeid_ = new ::std::string;
  }
  nodeid_->assign(value);
}
inline void MATSim2ExternHasSpace::set_nodeid(const char* value, size_t size) {
  set_has_nodeid();
  if (nodeid_ == &::google::protobuf::internal::kEmptyString) {
    nodeid_ = new ::std::string;
  }
  nodeid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* MATSim2ExternHasSpace::mutable_nodeid() {
  set_has_nodeid();
  if (nodeid_ == &::google::protobuf::internal::kEmptyString) {
    nodeid_ = new ::std::string;
  }
  return nodeid_;
}
inline ::std::string* MATSim2ExternHasSpace::release_nodeid() {
  clear_has_nodeid();
  if (nodeid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = nodeid_;
    nodeid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void MATSim2ExternHasSpace::set_allocated_nodeid(::std::string* nodeid) {
  if (nodeid_ != &::google::protobuf::internal::kEmptyString) {
    delete nodeid_;
  }
  if (nodeid) {
    set_has_nodeid();
    nodeid_ = nodeid;
  } else {
    clear_has_nodeid();
    nodeid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// MATSim2ExternHasSpaceConfirmed

// required bool hasSpace = 1;
inline bool MATSim2ExternHasSpaceConfirmed::has_hasspace() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MATSim2ExternHasSpaceConfirmed::set_has_hasspace() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MATSim2ExternHasSpaceConfirmed::clear_has_hasspace() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MATSim2ExternHasSpaceConfirmed::clear_hasspace() {
  hasspace_ = false;
  clear_has_hasspace();
}
inline bool MATSim2ExternHasSpaceConfirmed::hasspace() const {
  return hasspace_;
}
inline void MATSim2ExternHasSpaceConfirmed::set_hasspace(bool value) {
  set_has_hasspace();
  hasspace_ = value;
}

// -------------------------------------------------------------------

// MATSim2ExternPutAgentConfirmed

// -------------------------------------------------------------------

// Extern2MATSim_Agent

// required string id = 1;
inline bool Extern2MATSim_Agent::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Extern2MATSim_Agent::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Extern2MATSim_Agent::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Extern2MATSim_Agent::clear_id() {
  if (id_ != &::google::protobuf::internal::kEmptyString) {
    id_->clear();
  }
  clear_has_id();
}
inline const ::std::string& Extern2MATSim_Agent::id() const {
  return *id_;
}
inline void Extern2MATSim_Agent::set_id(const ::std::string& value) {
  set_has_id();
  if (id_ == &::google::protobuf::internal::kEmptyString) {
    id_ = new ::std::string;
  }
  id_->assign(value);
}
inline void Extern2MATSim_Agent::set_id(const char* value) {
  set_has_id();
  if (id_ == &::google::protobuf::internal::kEmptyString) {
    id_ = new ::std::string;
  }
  id_->assign(value);
}
inline void Extern2MATSim_Agent::set_id(const char* value, size_t size) {
  set_has_id();
  if (id_ == &::google::protobuf::internal::kEmptyString) {
    id_ = new ::std::string;
  }
  id_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Extern2MATSim_Agent::mutable_id() {
  set_has_id();
  if (id_ == &::google::protobuf::internal::kEmptyString) {
    id_ = new ::std::string;
  }
  return id_;
}
inline ::std::string* Extern2MATSim_Agent::release_id() {
  clear_has_id();
  if (id_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = id_;
    id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Extern2MATSim_Agent::set_allocated_id(::std::string* id) {
  if (id_ != &::google::protobuf::internal::kEmptyString) {
    delete id_;
  }
  if (id) {
    set_has_id();
    id_ = id;
  } else {
    clear_has_id();
    id_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string leaveNode = 2;
inline bool Extern2MATSim_Agent::has_leavenode() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Extern2MATSim_Agent::set_has_leavenode() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Extern2MATSim_Agent::clear_has_leavenode() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Extern2MATSim_Agent::clear_leavenode() {
  if (leavenode_ != &::google::protobuf::internal::kEmptyString) {
    leavenode_->clear();
  }
  clear_has_leavenode();
}
inline const ::std::string& Extern2MATSim_Agent::leavenode() const {
  return *leavenode_;
}
inline void Extern2MATSim_Agent::set_leavenode(const ::std::string& value) {
  set_has_leavenode();
  if (leavenode_ == &::google::protobuf::internal::kEmptyString) {
    leavenode_ = new ::std::string;
  }
  leavenode_->assign(value);
}
inline void Extern2MATSim_Agent::set_leavenode(const char* value) {
  set_has_leavenode();
  if (leavenode_ == &::google::protobuf::internal::kEmptyString) {
    leavenode_ = new ::std::string;
  }
  leavenode_->assign(value);
}
inline void Extern2MATSim_Agent::set_leavenode(const char* value, size_t size) {
  set_has_leavenode();
  if (leavenode_ == &::google::protobuf::internal::kEmptyString) {
    leavenode_ = new ::std::string;
  }
  leavenode_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Extern2MATSim_Agent::mutable_leavenode() {
  set_has_leavenode();
  if (leavenode_ == &::google::protobuf::internal::kEmptyString) {
    leavenode_ = new ::std::string;
  }
  return leavenode_;
}
inline ::std::string* Extern2MATSim_Agent::release_leavenode() {
  clear_has_leavenode();
  if (leavenode_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = leavenode_;
    leavenode_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Extern2MATSim_Agent::set_allocated_leavenode(::std::string* leavenode) {
  if (leavenode_ != &::google::protobuf::internal::kEmptyString) {
    delete leavenode_;
  }
  if (leavenode) {
    set_has_leavenode();
    leavenode_ = leavenode;
  } else {
    clear_has_leavenode();
    leavenode_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// Extern2MATSim

// required .Extern2MATSim.Agent agent = 15;
inline bool Extern2MATSim::has_agent() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Extern2MATSim::set_has_agent() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Extern2MATSim::clear_has_agent() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Extern2MATSim::clear_agent() {
  if (agent_ != NULL) agent_->::Extern2MATSim_Agent::Clear();
  clear_has_agent();
}
inline const ::Extern2MATSim_Agent& Extern2MATSim::agent() const {
  return agent_ != NULL ? *agent_ : *default_instance_->agent_;
}
inline ::Extern2MATSim_Agent* Extern2MATSim::mutable_agent() {
  set_has_agent();
  if (agent_ == NULL) agent_ = new ::Extern2MATSim_Agent;
  return agent_;
}
inline ::Extern2MATSim_Agent* Extern2MATSim::release_agent() {
  clear_has_agent();
  ::Extern2MATSim_Agent* temp = agent_;
  agent_ = NULL;
  return temp;
}
inline void Extern2MATSim::set_allocated_agent(::Extern2MATSim_Agent* agent) {
  delete agent_;
  agent_ = agent;
  if (agent) {
    set_has_agent();
  } else {
    clear_has_agent();
  }
}

// -------------------------------------------------------------------

// Extern2MATSimConfirmed

// required bool accepted = 1;
inline bool Extern2MATSimConfirmed::has_accepted() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Extern2MATSimConfirmed::set_has_accepted() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Extern2MATSimConfirmed::clear_has_accepted() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Extern2MATSimConfirmed::clear_accepted() {
  accepted_ = false;
  clear_has_accepted();
}
inline bool Extern2MATSimConfirmed::accepted() const {
  return accepted_;
}
inline void Extern2MATSimConfirmed::set_accepted(bool value) {
  set_has_accepted();
  accepted_ = value;
}

// -------------------------------------------------------------------

// ExternSimStepFinished

// required double time = 1;
inline bool ExternSimStepFinished::has_time() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ExternSimStepFinished::set_has_time() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ExternSimStepFinished::clear_has_time() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ExternSimStepFinished::clear_time() {
  time_ = 0;
  clear_has_time();
}
inline double ExternSimStepFinished::time() const {
  return time_;
}
inline void ExternSimStepFinished::set_time(double value) {
  set_has_time();
  time_ = value;
}

// -------------------------------------------------------------------

// ExternSimStepFinishedReceived

// -------------------------------------------------------------------

// ExternDoSimStep

// required double fromTime = 1;
inline bool ExternDoSimStep::has_fromtime() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ExternDoSimStep::set_has_fromtime() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ExternDoSimStep::clear_has_fromtime() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ExternDoSimStep::clear_fromtime() {
  fromtime_ = 0;
  clear_has_fromtime();
}
inline double ExternDoSimStep::fromtime() const {
  return fromtime_;
}
inline void ExternDoSimStep::set_fromtime(double value) {
  set_has_fromtime();
  fromtime_ = value;
}

// required double toTime = 2;
inline bool ExternDoSimStep::has_totime() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ExternDoSimStep::set_has_totime() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ExternDoSimStep::clear_has_totime() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ExternDoSimStep::clear_totime() {
  totime_ = 0;
  clear_has_totime();
}
inline double ExternDoSimStep::totime() const {
  return totime_;
}
inline void ExternDoSimStep::set_totime(double value) {
  set_has_totime();
  totime_ = value;
}

// -------------------------------------------------------------------

// ExternDoSimStepReceived

// -------------------------------------------------------------------

// ExternalConnect

// -------------------------------------------------------------------

// ExternalConnectConfirmed

// -------------------------------------------------------------------

// ExternOnPrepareSim

// -------------------------------------------------------------------

// ExternOnPrepareSimConfirmed

// -------------------------------------------------------------------

// ExternAfterSim

// -------------------------------------------------------------------

// ExternAfterSimConfirmed

// -------------------------------------------------------------------

// AgentsStuck

// repeated string agentId = 1;
inline int AgentsStuck::agentid_size() const {
  return agentid_.size();
}
inline void AgentsStuck::clear_agentid() {
  agentid_.Clear();
}
inline const ::std::string& AgentsStuck::agentid(int index) const {
  return agentid_.Get(index);
}
inline ::std::string* AgentsStuck::mutable_agentid(int index) {
  return agentid_.Mutable(index);
}
inline void AgentsStuck::set_agentid(int index, const ::std::string& value) {
  agentid_.Mutable(index)->assign(value);
}
inline void AgentsStuck::set_agentid(int index, const char* value) {
  agentid_.Mutable(index)->assign(value);
}
inline void AgentsStuck::set_agentid(int index, const char* value, size_t size) {
  agentid_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* AgentsStuck::add_agentid() {
  return agentid_.Add();
}
inline void AgentsStuck::add_agentid(const ::std::string& value) {
  agentid_.Add()->assign(value);
}
inline void AgentsStuck::add_agentid(const char* value) {
  agentid_.Add()->assign(value);
}
inline void AgentsStuck::add_agentid(const char* value, size_t size) {
  agentid_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
AgentsStuck::agentid() const {
  return agentid_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
AgentsStuck::mutable_agentid() {
  return &agentid_;
}

// -------------------------------------------------------------------

// AgentsStuckConfirmed


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MATSimInterface_2eproto__INCLUDED
