# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - mkdir --parents $READTHEDOCS_OUTPUT/html/
    - wget -O ${READTHEDOCS_GIT_COMMIT_HASH}.tar  https://fz-juelich.sciebo.de/s/99uKnQ6xa1Knmlg/download\?path\=%2F\&files\=${READTHEDOCS_GIT_COMMIT_HASH}.tar
    - tar xf ${READTHEDOCS_GIT_COMMIT_HASH}.tar
    - mv readthedocs/build/* $READTHEDOCS_OUTPUT/html/

# Build no formats
formats: [ ]

