language: cpp

git:
  depth: 1
  quiet: true

matrix:
  include:
    - name: linux (clang8)
      os: linux
      dist: bionic
      env: TOOLCHAIN=clang
      script:
       - ./scripts/setup-deps.sh
       - mkdir build && cd build
       - cmake  .. -DCMAKE_PREFIX_PATH=$(pwd)/../deps -DBUILD_CPPUNIT_TEST=ON -DAIROUTER=ON -DJPSFIRE=ON
       - make -j $(nproc)
       - CTEST_OUTPUT_ON_FAILURE=1 ctest -j 2
       - bin/jpscore $(pwd)/../demos/scenario_2_bottleneck/bottleneck_ini.xml

    - name: linux (gcc9)
      os: linux
      dist: bionic
      env: TOOLCHAIN=gcc
      script:
       - ./scripts/setup-deps.sh
       - mkdir build && cd build
       - cmake .. -DCMAKE_PREFIX_PATH=$(pwd)/../deps -DBUILD_CPPUNIT_TEST=ON -DAIROUTER=ON -DJPSFIRE=ON
       - make -j $(nproc)
       - CTEST_OUTPUT_ON_FAILURE=1 ctest -j 2
       - bin/jpscore $(pwd)/../demos/scenario_2_bottleneck/bottleneck_ini.xml

    - name: mac (appleclang)
      os: osx
      osx_image: xcode10.2
      env: TOOLCHAIN=clang
      script:
        - ./scripts/setup-deps.sh
        - mkdir build && cd build
        - cmake .. -DCMAKE_PREFIX_PATH=$(pwd)/../deps -DBUILD_CPPUNIT_TEST=ON -DAIROUTER=ON -DJPSFIRE=ON
        - make -j $(nproc)
        - CTEST_OUTPUT_ON_FAILURE=1 ctest -j 2
        - bin/jpscore $(pwd)/../demos/scenario_2_bottleneck/bottleneck_ini.xml

before_install:
  - source .travis_before_install.bash

install:
  - source .travis_install.bash
