name: 'Download Workflow Run Artifact'
description: 'Downloads an artifact from a workflow run by name'

inputs:
  run-id:
    description: 'Run ID of the workflow that created the artifact'
    required: true
  artifact-name:
    description: 'Name of the artifact to download'
    required: true
  download-path:
    description: 'Path to download and extract the artifact'
    required: false
    default: '.'
  github-token:
    description: 'GitHub token for API authentication'
    required: true

outputs:
  download-path:
    description: 'Path where the artifact was extracted'
    value: ${{ steps.download-artifact.outputs.download-path }}

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.14'

    - name: Install dependencies
      shell: bash
      run: |
        python3 -m pip install --quiet requests

    - name: Download artifact
      id: download-artifact
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        ${{ github.action_path }}/download-artefact.py \
          --run-id "${{ inputs.run-id }}" \
          --artifact-name "${{ inputs.artifact-name }}" \
          --download-path "${{ inputs.download-path }}" \
          --repository "${{ github.repository }}"
