name: Build Documentation for PR
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  build:
    name: Build documentation for PR
    runs-on: ubuntu-latest
    outputs:
      artifact-id: ${{ steps.build-docs.outputs.artifact-id }}
      pr-number: ${{ github.event.pull_request.number }}
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4

      - name: Build documentation
        id: build-docs
        uses: ./.github/actions/build-docs
        with:
          python-version: "3.13"
          docs-requirements-path: "docs/requirements.txt"
          docs-source-path: "docs/source"
          docs-build-path: "docs/build"
          retention-days: "1"
  call-preview-wf:
    uses: ./.github/workflows/pr-preview.yml
    needs: build
    with:
      triggering-run-id: ${{ github.run_id }}
      artifact-id: ${{ needs.build.outputs.artifact-id }}
      pr-number: ${{ needs.build.outputs.pr-number }}
